# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 574f008767d08cc061d5e8b5d5a52b14438f0ba046e53371d9df372abe294d5568aede58a0d2d1ebbc98e543b5f3ac0b94e62d9ffec7732ec4c20d36adb5eaab

test:
  secret_key_base: 1e4678c5a4dbca9422387c67d41af8cc57cdfaeba6f48461a089c74af7332f6de60778a13785b32011f72763df7dcb33c68c77d1e2eddc79bd24e886ec662c88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
